#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
	echo "Workspace $1 is focused"
	sketchybar --set $NAME background.drawing=on
else
	sketchybar --set $NAME background.drawing=off
fi

create_workspace_bracket_for_monitor() {
	parameters=("$@")
	monitor_id=${parameters[0]}
	monitor_workspaces=("${parameters[@]:1}")

	if [ $monitor_id -eq 1 ]; then
		sketchybar --add item workspaces_spacer_left left \
			--set workspaces_spacer_left \
			width=4 \
			background.drawing=off \
			label.drawing=off
	fi

	for workspace_id in ${monitor_workspaces[@]}; do
		sketchybar --add item workspaces."$monitor_id"."$workspace_id" left \
			--subscribe workspaces."$monitor_id"."$workspace_id" aerospace_workspace_change \
			--set workspaces."$monitor_id"."$workspace_id" \
			background.drawing=off \
			click_script="aerospace workspace $workspace_id" \
			label="$workspace_id" \
			label.width="25" \
			script="$PLUGIN_DIR/aerospace $workspace_id"
	done

	if [ $monitor_id -lt ${#monitor_ids[@]} ]; then
		sketchybar --add item workspaces_monitor_separator."$monitor_id" left \
			--set workspaces_monitor_separator."$monitor_id" \
			background.drawing=off \
			label.padding_left=-6 \
			label.font.size="$BACKGROUND_HEIGHT" \
			label="|"
	else
		sketchybar --add item workspaces_service_mode left \
			--subscribe workspaces_service_mode aerospace_service_mode_enabled_changed \
			--set workspaces_service_mode \
			background.drawing=off \
			label.drawing=off \
			label.highlight=on \
			label.font="$LABEL_HIGHLIGHT_FONT" \
			label="[s]" \
			label.padding_right=10 \
			script="$PLUGIN_DIR/aerospace $AEROSPACE_SERVICE_MODE_ENABLED"

		sketchybar --add item workspaces_spacer_right left \
			--set workspaces_spacer_right \
			width=4 \
			background.drawing=off \
			label.drawing=off
	fi

	sketchybar --add bracket workspaces."$monitor_id" /workspaces\.*/ \
		--set workspaces."$monitor_id" \
		background.padding_left="50" \
		background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
		background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"
}

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_service_mode_enabled_changed

monitor_ids=($(aerospace list-monitors | awk '{print $1}'))

# TODO:
# - Update this view when moving workspaces to a different monitors.
# - Only show workspaces with active windows or currently selected like in i3
#   default configuration.
for monitor_id in ${monitor_ids[@]}; do
	workspaces_for_monitor_id=($(aerospace list-workspaces --monitor $monitor_id))
	create_workspace_bracket_for_monitor $monitor_id "${workspaces_for_monitor_id[@]}"
done
