"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 2

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
background = "#d3d7cf"
foreground = "#000000"
leading_diamond = "╭─"
style = "diamond"
template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
type = "os"

[[blocks.segments]]
background = "#3465a4"
foreground = "#e4e4e4"
powerline_symbol = ""
style = "powerline"
template = "  {{ .Path }} "
type = "path"

[blocks.segments.properties]
home_icon = "~"
style = "full"

[[blocks.segments]]
background = "#4e9a06"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}",
  "{{ if gt .Ahead 0 }}#89d1dc{{ end }}",
  "{{ if gt .Behind 0 }}#4e9a06{{ end }}",
]
foreground = "#000000"
powerline_symbol = ""
style = "powerline"
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
type = "git"

[blocks.segments.properties]
branch_icon = " "
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true

[[blocks]]
alignment = "right"
type = "prompt"

[[blocks.segments]]
background = "#689f63"
foreground = "#ffffff"
invert_powerline = true
powerline_symbol = ""
style = "powerline"
template = " {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}  "
type = "node"

[blocks.segments.properties]
fetch_version = true

[[blocks.segments]]
background = "#00acd7"
foreground = "#111111"
invert_powerline = true
powerline_symbol = ""
style = "powerline"
template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  "
type = "go"

[blocks.segments.properties]
fetch_version = true

[[blocks.segments]]
background = "#4063D8"
foreground = "#111111"
invert_powerline = true
powerline_symbol = ""
style = "powerline"
template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  "
type = "julia"

[blocks.segments.properties]
fetch_version = true

[[blocks.segments]]
background = "#FFDE57"
foreground = "#111111"
invert_powerline = true
powerline_symbol = ""
style = "powerline"
template = " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}  "
type = "python"

[blocks.segments.properties]
display_mode = "context"
display_default = true
fetch_virtual_env = true
folder_name_fallback = true
home_enabled = true

[[blocks.segments]]
background = "#FEAC19"
foreground = "#ffffff"
invert_powerline = true
powerline_symbol = ""
style = "powerline"
template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
type = "azfunc"

[blocks.segments.properties]
display_mode = "files"
fetch_version = false

[[blocks.segments]]
background_templates = [
  "{{if contains \"default\" .Profile}}#FFA400{{end}}",
  "{{if contains \"jan\" .Profile}}#f1184c{{end}}",
]
foreground = "#ffffff"
invert_powerline = true
powerline_symbol = ""
style = "powerline"
template = " {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}  "
type = "aws"

[blocks.segments.properties]
display_default = false

[[blocks.segments]]
background = "#ffff66"
foreground = "#111111"
invert_powerline = true
powerline_symbol = ""
style = "powerline"
template = "  "
type = "root"

[[blocks.segments]]
background = "#c4a000"
foreground = "#000000"
invert_powerline = true
powerline_symbol = ""
style = "powerline"
template = " {{ .FormattedMs }}  "
type = "executiontime"

[[blocks.segments]]
background = "#000000"
background_templates = ["{{ if gt .Code 0 }}#cc2222{{ end }}"]
foreground = "#d3d7cf"
invert_powerline = true
powerline_symbol = ""
style = "powerline"
template = " {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} "
type = "status"

[blocks.segments.properties]
always_enabled = true

# [[blocks.segments]]
# background = "#d3d7cf"
# foreground = "#000000"
# invert_powerline = true
# style = "diamond"
# template = " {{ .CurrentDate | date .Format }}  "
# trailing_diamond = "─╮"
# type = "time"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#d3d7cf"
style = "plain"
template = "╰─"
type = "text"

[[blocks]]
type = "rprompt"

[[blocks.segments]]
foreground = "#d3d7cf"
style = "plain"
template = "─╯"
type = "text"
