#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..





cd "$(dirname $0)"/..
DOTFILES_ROOT=$(pwd -P)

# find the installers and run them iteratively
run_installers() {
	find . -name install.sh | while read installer; do
		echo "Going to install $installer"
		sh -c "${installer}"
	done
}

install_packages() {
	local installers=(system ruby node python) system_packages='' ruby_packages='' npm_packages='' python_packages='' postfix=_packages
	for installer in "${installers[@]}"; do
		for packages in $(find -H "$DOTFILES_ROOT" -name $installer$postfix); do
			for package in "$(cat $packages)"; do
				case $installer in
				system)
					system_packages+=" $package"
					;;
				ruby)
					ruby_packages+=" $package"
					;;
				node)
					npm_packages+=" $package"
					;;
				python)
					python_packages+=" $package"
					;;
				esac
			done
		done
	done
	echo $system_packages
  if [[ "$OSTYPE" == "darwin"* ]]; then
    # Run Homebrew through the Brewfile
    echo "› brew bundle"
    brew bundle
  fi
	# sudo dnf install -y ${system_packages[@]} --allowerasing
	run_installers
	echo $ruby_packages
	gem install --user ${ruby_packages[@]}
	echo $npm_packages
	yarn global add ${npm_packages[@]}
	echo $python_packages
	pip3 install --user ${python_packages[@]}

	echo 'Done, you need to logout and in to source `.zprofile`'
}
install_packages
