require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colors"
require "user.bufferline"
require "user.completion"
require "user.autopairs"
require "user.lsp"
require "user.alpha"
require "user.nvim-tree"
require "user.toggle-term"
-- require "user.whichkey"
require "user.treesitter"
require "user.gitsigns"
require "user.neoclip"
require "user.comment"

